### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by r4nd0m** [quetwo/railoWebSocketServer#2]
Hi there,

I encountered a problem while being used this extension together with Railo. Unfortunately, I don't have time to look into it deeper (so the problem can be also caused by Railo). There are some screenshots, perhaps it'll help somehow:
![leak](https://cloud.githubusercontent.com/assets/1593031/10242946/0d4da6c8-68f5-11e5-8c48-16266b0a82f5.png)
![leak2](https://cloud.githubusercontent.com/assets/1593031/10243014/bde66b96-68f5-11e5-997c-1b34ae147bfe.png)
![leak3](https://cloud.githubusercontent.com/assets/1593031/10243013/bde0f6a2-68f5-11e5-97bd-99c782afc62c.png)

Best regards,

**Comment by quetwo** [comment]
Thanks for the detailed report.  Do you know how many channels you are "watching" from within Railo?  

If there would be a memory leak, I would expect it to be in the the com.quetwo.\* java.

What looks like is happening is that the garbage collection isn't running on the driver or your custom code that reacts to the incoming messages.  There is some CFML code that seems to be the issue based on your output.

**Comment by r4nd0m** [comment]
I didn't count actually but i think no more than 200 channels.
I don't think that the leak comes from my custom code since i only used SendGatewayMessage(). I tried to to fix it by updating the watcher and listener cfc's (like setting output="no" for the whole component and setting the scope for some variables explicitly), but it didn't help.
It became a bit better after setting whitespace management in Railo, but unfortunately it's not an option for our project. So for now we'we just moved to a Tomcat websocket API.

**Comment by quetwo** [comment]
It looks like this was fixed in Lucee 4.5.0.03.  There was an issue where it would buffer the thread that the gateways ran in even though that should be thrown out.  Since Railo hasn't back-ported any of the fixes into that project it looks like you would need to upgrade to Lucee.  

This does seem to happen, regardless of the number of channels you watch.  It happens faster if you have a larger number of channels being watched since the code does loop over that (generating more whitespace in the buffer).

**Comment by r4nd0m** [comment]
Hi. Unfortunately, I failed to install and test it in Lucee. Anyways, thanks for the feedback.
